# .github/dependabot.yml
version: 2

updates:
  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(security): "
      prefix-development: "chore(dep): "
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      # Version updates for patch releases are safe to auto merge because
      # patches usually don't introduce new features or behaviours.
      safe-updates-version:
        applies-to: version-updates
        update-types:
          - patch
      # Security updates for patch and minor releases should be auto merged
      # to mitigate the vulnerabilities that they expose the application to.
      # These updates usually don't introduce new features or behaviours.
      safe-updates-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor

  # Check for Node.js updates (grouped as patch)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(security): "
      prefix-development: "chore(dep): "
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      # Version updates for patch releases are safe to auto merge because
      # patches usually don't introduce new features or behaviours.
      safe-updates-version:
        applies-to: version-updates
        update-types:
          - patch
      # Security updates for patch and minor releases should be auto merged
      # to mitigate the vulnerabilities that they expose the application to.
      # These updates usually don't introduce new features or behaviours.
      safe-updates-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
