name: Continous Security Integration
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

  schedule:
    - cron: "30 2 * * *" # for scheduled security scans

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        id: deps
        with:
          scan-type: fs
          scanners: "vuln"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        id: deps
        with:
          scan-type: fs
          scanners: "secret,misconfig"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
