name: Continous Security Integration
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

  schedule:
    - cron: "30 2 * * *" # for scheduled security scans

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        id: deps
        with:
          scan-type: fs
          scanners: "vuln"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        id: deps
        with:
          scan-type: fs
          scanners: "secret,misconfig"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
