name: Continuous Integration
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

jobs:
  check-commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # fetch all history for commitlint to work

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: latest

      - name: Install commitlint
        run: |
          npm install commitlint@latest @commitlint/config-conventional

      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose

      - name: Lint PR commits
        if: github.event_name == 'pull_request' && github.event.action != 'edited'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
